# Generated by Django 4.0 on 2022-01-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='girdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('bugunkuVaka', models.PositiveIntegerField()),
                ('bugunkuHasta', models.PositiveIntegerField()),
                ('bugunkuTest', models.PositiveIntegerField()),
                ('bugunkuVefat', models.PositiveIntegerField()),
                ('bugunkuIyilesen', models.PositiveIntegerField()),
                ('agirHasta', models.PositiveIntegerField()),
            ],
        ),
    ]
