# Generated by Django 4.0 on 2022-01-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_ozelgunler'),
    ]

    operations = [
        migrations.AddField(
            model_name='girdi',
            name='kullanici',
            field=models.CharField(default=1, editable=False, max_length=100, verbose_name='auth.User'),
            preserve_default=False,
        ),
    ]
